INSERT INTO GENRE (NAME) VALUES ('COMEDY');
INSERT INTO GENRE (NAME) VALUES ('DRAMA');
INSERT INTO GENRE (NAME) VALUES ('ANIMATION');
INSERT INTO GENRE (NAME) VALUES ('THRILLER');
INSERT INTO GENRE (NAME) VALUES ('DOCUMENTARY');
INSERT INTO GENRE (NAME) VALUES ('ACTION');

INSERT INTO MPA_RATING (NAME) VALUES ('G');
INSERT INTO MPA_RATING (NAME) VALUES ('PG');
INSERT INTO MPA_RATING (NAME) VALUES ('PG13');
INSERT INTO MPA_RATING (NAME) VALUES ('R');
INSERT INTO MPA_RATING (NAME) VALUES ('NC17');



