CREATE TABLE IF NOT EXISTS "FILM"
(
    "ID"
    INT
    AUTO_INCREMENT
    PRIMARY
    KEY,
    "NAME"
    VARCHAR,
    "DESCRIPTION"
    VARCHAR,
    "DURATION"
    INT,
    "RELEASEDATE"
    DATE,
    "RATING_ID"
    INT
);
CREATE TABLE IF NOT EXISTS "GENRE"
(
    "ID"
    INT
    AUTO_INCREMENT
    PRIMARY
    KEY,
    "NAME"
    VARCHAR
);
CREATE TABLE IF NOT EXISTS "FILM_X_GENRE"
(
    "FILM_ID"
    INT,
    "GENRE_ID"
    INT
);
CREATE TABLE IF NOT EXISTS "MPA_RATING"
(
    "ID"
    INT
    AUTO_INCREMENT
    PRIMARY
    KEY,
    "NAME"
    VARCHAR
);
CREATE TABLE IF NOT EXISTS "APP_USER"
(
    "ID"
    INT
    AUTO_INCREMENT
    PRIMARY
    KEY,
    "NAME"
    VARCHAR,
    "LOGIN"
    VARCHAR,
    "EMAIL"
    VARCHAR,
    "BIRTHDAY"
    DATE
);
CREATE TABLE IF NOT EXISTS "FILM_X_USER"
(
    "FILM_ID"
    INT,
    "USER_ID"
    INT
);
CREATE TABLE IF NOT EXISTS "CONNECTION"
(
    "USER1_ID"
    INT,
    "USER2_ID"
    INT,
    "STATUS"
    BOOLEAN
    NOT
    NULL
);

ALTER TABLE "FILM_X_GENRE"
    ADD FOREIGN KEY ("GENRE_ID") REFERENCES "GENRE" ("ID");

ALTER TABLE "FILM_X_GENRE"
    ADD FOREIGN KEY ("FILM_ID") REFERENCES "FILM" ("ID");

ALTER TABLE "FILM"
    ADD FOREIGN KEY ("RATING_ID") REFERENCES "MPA_RATING" ("ID");

ALTER TABLE "FILM_X_USER"
    ADD FOREIGN KEY ("FILM_ID") REFERENCES "FILM" ("ID");

ALTER TABLE "FILM_X_USER"
    ADD FOREIGN KEY ("USER_ID") REFERENCES "APP_USER" ("ID");

ALTER TABLE "CONNECTION"
    ADD FOREIGN KEY ("USER1_ID") REFERENCES "APP_USER" ("ID");

ALTER TABLE "CONNECTION"
    ADD FOREIGN KEY ("USER2_ID") REFERENCES "APP_USER" ("ID");